export const models = [
  {
    name: "Task",
    pubSub: {
      publishCreate: true,
      publishUpdate: true,
      publishDelete: true
    },
    // this auth config piece should be generated by the graphback plugin
    // we can discuss whether that's directives or annotations
    auth: {
      rules: [
        {
          allow: 'owner',
          operations: ['update', 'create', 'read', 'delete'],
          ownerField: 'owner',
        },
        {
          allow: 'role',
          operations: ['update', 'delete'],
          roles: ["admin"]
        }
      ]
    }
  }
]
