/*
 * File generated by Graphback CRUD resolver plugin.
 * Content will be overwritten by Graphback generator.
 * To change implementation please disable generator options and supply your own implementation
 * outside generated file.
 */

export default {
  Task: {
    comments: (parent, args, context) => {
      return context.Comment.batchLoadData("noteId", parent._id, context)
    },
  },

  Comment: {
    note: (parent, args, context) => {
      return context.Task.findBy({ _id: parent.noteId }).then(
        (results) => results[0]
      )
    },
  },

  Query: {
    findTasks: (parent, args, context) => {
      const { fields, ...page } = args
      return context.Task.findBy(fields, page)
    },
    findAllTasks: (parent, args, context) => {
      return context.Task.findAll(args)
    },
  },

  Mutation: {
    createTask: (parent, args, context) => {
      return context.Task.create(args.input, context)
    },
    updateTask: (parent, args, context) => {
      return context.Task.update(args.input, context)
    },
    deleteTask: (parent, args, context) => {
      return context.Task.delete(args.input, context)
    },
    createComment: (parent, args, context) => {
      return context.Comment.create(args.input, context)
    },
  },

  Subscription: {
    newTask: {
      subscribe: (parent, args, context) => {
        return context.Task.subscribeToCreate(args, context)
      },
    },
    updatedTask: {
      subscribe: (parent, args, context) => {
        return context.Task.subscribeToUpdate(args, context)
      },
    },
    deletedTask: {
      subscribe: (parent, args, context) => {
        return context.Task.subscribeToDelete(args, context)
      },
    },
    newComment: {
      subscribe: (parent, args, context) => {
        return context.Comment.subscribeToCreate(args, context)
      },
    },
  },
}
