fragment TaskFields on Task { 
    id
    version 
    title 
    description
    status
    deleted
    lastModified
}

fragment TaskConnectionFields on TaskConnection{
  items{
    ...TaskFields
  }
  startedAt
}

mutation createTask {
  createTask(title: "Task1", description: "test", status: OPEN) {
     ...TaskFields
  }
}

mutation updateTask {
  updateTask(id: "5e29da2de4fa0030b90a58d9", title: "Task2", version: 1) {
    ...TaskFields
  }
}

mutation deleteTask {
  deleteTask(id: "5e29da5f78d59530f4284a34")
}

query getTask {
  getTask(id: "5e29da5f78d59530f4284a34") {
    ...TaskFields
  }
}

query allTasks {
  allTasks(lastSync:"157980147900"){
    ...TaskConnectionFields
  }
}