mutation create {
  createTask(input: { title: "test", 
    description: "" }) {
    id
  }
}


mutation update {
  updateTask(input:{id:"5ee7a3e5e1479c83e4f1748f",  
    title: "test", description: ""}){
    id
    type
  }
}



query syncTasks{
  syncTasks(lastSync: "1592239061067"){
    items{
      id
      title
    }
    lastSync
  }
}


query find {
  findTasks{
    items{
      id
      title
    }
  }
}